In [2]:
#import dependencies
import pandas as pd
import numpy
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
#declare csv's and read into pandas DF(Extract data)
csv_file_cancer = "incd_cancer_2016.csv"
csv_file_pollution = "pollution_us_2010.csv"
cancer_df = pd.read_csv(csv_file_cancer, encoding = 'unicode_escape')
pollution_df = pd.read_csv(csv_file_pollution)

In [4]:
#Transform data by cleaning into new df's with desired columns only
cancer_clean = cancer_df[['State', 'Incidence Rate- cases per 100,000', 'Average Annual Count', 'Recent Trend', 'Recent 5-Year Trend']]
sorted_cancer = cancer_clean.sort_values(by='Incidence Rate- cases per 100,000', ascending=False)
sorted_cancer

,State,"Incidence Rate- cases per 100,000",Average Annual Count,Recent Trend,Recent 5-Year Trend
1,"Kentucky(7,8)",509.7,27135,stable,-0.1
2,"Delaware(2,10)",487.2,6001,stable,-0.9
3,"Pennsylvania(2,10)",482.5,80089,stable,-0.3
4,"New Hampshire(2,10)",480.9,8442,stable,-0.8
5,"New York(7,8)",474.8,113026,falling,-0.9
6,"New Jersey(7,8)",474.6,51492,falling,-7.9
7,"Iowa(7,8)",473.6,18146,falling,-0.2
8,"Maine(2,10)",473.4,8901,stable,-0.1
9,"Louisiana(7,8)",472.2,25402,falling,-0.8
10,"West Virginia(2,10)",472,11698,stable,-0.3
11,"Arkansas(2,10)",469.6,17053,stable,0.8
12,"Georgia(7,8)",468.8,52056,falling,-0.3
13,"Mississippi(2,10)",465.8,16265,stable,-0.3
14,"Connecticut(7,8)",465.5,21117,falling,-1.4
15,"Illinois(2,10)",462.8,68954,stable,-0.1
16,"Wisconsin(2,10)",458.6,32688,stable,-0.4
17,"North Carolina(2,10)",458.4,55394,stable,-0.3
18,"Alabama(2,10)",457.8,27195,stable,-0.1
19,"Kansas(2,10)",457.3,15312,stable,-0.5
20,"Montana(2,10)",456.6,6194,stable,0.6
21,"Ohio(2,10)",456.1,65645,stable,0.2
22,"Tennessee(2,10)",455.7,36598,stable,-0.4
23,"Minnesota(2,10)",455.7,29619,stable,0.0
24,"Rhode Island(2,10)",450.6,5972,falling,-2.3
25,"South Dakota(2,10)",449.5,4612,stable,-0.8
26,"North Dakota(2,10)",448.7,3765,stable,-0.9
27,"Oklahoma(2,10)",447.9,20167,stable,-0.1
28,"Nebraska(2,10)",446.4,9838,stable,0.1
29,"Missouri(2,10)",446.3,33171,stable,-0.7
30,"Washington(4,10)",445.1,37378,falling,-1.4
31,"Indiana(2,10)",443,34260,stable,-0.3
32,"Vermont(2,10)",442.4,3681,stable,-0.9
33,"South Carolina(2,10)",440.9,27313,stable,-0.9
34,"Maryland(2,10)",440.9,30942,stable,-0.6
35,"Idaho(7,8)",439.2,8354,stable,-0.1
36,"Michigan(4,10)",436.8 #,53911,falling,-1.3
0,"US (SEER+NPCR)(1,10)",435.6,1658716,falling,-0.9
37,"Florida(2,10)",419.3,119408,stable,-1.6
38,"Hawaii(7,8)",414.2,7395,stable,1.0
39,"Virginia(2,10)",413.3,40322,stable,-0.6
40,"Alaska(2,10)",405.8,2882,stable,-0.8
41,"Oregon(2,10)",405.3,20596,falling,-2.3
42,"Massachusetts(7,8)",404.5,33662,falling,-2.4
43,"Wyoming(2,10)",402.3,2775,stable,0.4
44,"Texas(2,10)",391.8,109083,falling,-1.4
45,"Utah(7,8)",390.2,10484,falling,-1.3
46,"Colorado(2,10)",388.8,23244,falling,-1.5
47,"California(7,8)",385.6,164889,falling,-1.8
48,"Nevada(2,10)",385,13054,stable,-1.9
49,"District of Columbia(2,10)",378.3,2566,falling,-6.2
50,"Arizona(2,10)",376.3,31443,stable,-0.9
51,"New Mexico(7,8)",359.4,9075,falling,-1.7
52,"Puerto Rico(2,10)",358,15930,stable,-0.1

In [7]:
pollution_clean = pollution_df[['State', 'NO2 Units', 'NO2 Mean', 'O3 Units', 'O3 Mean', 'SO2 Units', 'SO2 Mean', 'CO Units', 'CO Mean']]
pollution_group = pollution_clean.groupby(['State'])
pollution_state = pollution_group.mean()
pollution_state

                       NO2 Mean   O3 Mean  SO2 Mean   CO Mean
State
Arizona               15.916712  0.025903  1.047033  0.365168
Arkansas              10.004749  0.027650  1.292494  0.454634
California            12.247269  0.025669  0.720866  0.344747
Colorado              16.171138  0.022955  1.028090  0.365696
Connecticut            9.739028  0.027474  0.949623  0.279957
District Of Columbia  17.643918  0.028240  3.360865  0.883861
Florida                5.672489  0.028882  0.147791  0.394005
Georgia               16.500656  0.016584  1.147945  0.396889
Idaho                  9.397005  0.026446  0.323220  0.179643
Illinois              13.035390  0.026312  2.108131  0.347147
Indiana                9.392295  0.029450  2.985985  0.164237
Iowa                   7.497583  0.028709  0.386309  0.250279
Kansas                13.066675  0.021598  5.189309  0.417027
Louisiana             12.698543  0.025292  1.359625  0.247255
Maine                  6.161710  0.026202  0.940155  0.252701
Maryland              13.066960  0.028370  2.152991  0.391471
Massachusetts         17.052750  0.022202  1.580872  0.280420
Nevada                22.342167  0.018229  0.430436  0.289673
New Hampshire          7.668571  0.029612  0.973383  0.442154
New York              12.980506  0.028121  3.039182  0.304924
North Carolina        11.689251  0.028405  0.904412  0.328667
North Dakota           5.418302  0.026455  0.281607  0.171878
Ohio                   5.079082  0.038088  1.473980  0.322609
Oklahoma               6.441628  0.029255  0.793962  0.217853
Oregon                 9.542009  0.021389  1.334737  0.336610

In [6]:
merge_df = pd.merge(sorted_cancer, pollution_state, how='outer', on=['State'])
merge_df.round(4)

,State,"Incidence Rate- cases per 100,000",Average Annual Count,Recent Trend,Recent 5-Year Trend,NO2 Mean,O3 Mean,SO2 Mean,CO Mean
0,"Kentucky(7,8)",509.7,27135.0,stable,-0.1,NaN,NaN,NaN,NaN
1,"Delaware(2,10)",487.2,6001.0,stable,-0.9,NaN,NaN,NaN,NaN
2,"Pennsylvania(2,10)",482.5,80089.0,stable,-0.3,NaN,NaN,NaN,NaN
3,"New Hampshire(2,10)",480.9,8442.0,stable,-0.8,NaN,NaN,NaN,NaN
4,"New York(7,8)",474.8,113026.0,falling,-0.9,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
73,North Carolina,NaN,NaN,NaN,NaN,11.6893,0.0284,0.9044,0.3287
74,North Dakota,NaN,NaN,NaN,NaN,5.4183,0.0265,0.2816,0.1719
75,Ohio,NaN,NaN,NaN,NaN,5.0791,0.0381,1.4740,0.3226
76,Oklahoma,NaN,NaN,NaN,NaN,6.4416,0.0293,0.7940,0.2179
77,Oregon,NaN,NaN,NaN,NaN,9.5420,0.0214,1.3347,0.3366